server:
  port: 8080  #¶Ë¿Ú

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #static-path-pattern: /WEB-INF/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root